allowed_games = [
    "Starfield Digital Premium Edition",
    "Warhammer 40.000: Dawn of War II Master Collection",
    "Risen 2: Dark Waters",
    "Call of Juarez: Bound in Blood",
    "Farming Simulator 22 - Premium Edition",
    "Old World - The Sacred and The Profane",
    "Endzone - A World Apart Complete Edition",
    "Prison Simulator",
    "Cities: Skylines - Content Creator Pack: Seaside Resorts",
    "SBK 22",
    "Earth Defense Force 5",
    "The Jackbox Party Pack 8",
    "NBA 2K22",
    "Patrician III",
    "Ride 5",
    "Journey to the Savage Planet",
    "Destiny 2: Legendary Edition",
    "Pure Farming 2018 - Digital Deluxe Edition",
    "Total War: Rome II - Wrath of Sparta",
    "Sword Art Online: Alicization Lycoris Deluxe Edition",
    "Sniper Ghost Warrior 3",
    "Panzer Corps 2",
    "Overcooked! 2 - Carnival of Chaos",
    "Sacred Gold",
    "No Man's Sky",
    "Gloomhaven",
    "Treasure Hunter Simulator",
    "Dead by Daylight: The 80's Suitcase",
    "BlazBlue: Centralfiction",
    "Tropico 5",
    "Tannenberg",
    "LEGO Marvel Super Heroes 2",
    "The Jackbox Party Pack 3",
    "Marvel's Avengers - The Definitive Edition",
    "Sid Meier’s Civilization VI: Leader Pass",
    "Frozen Flame",
    "MotoGP 23",
    "The Jackbox Party Quintpack",
    "Autobahn Police Simulator 3",
    "Orcs Must Die! 3 - Cold as Eyes",
    "Creaks",
    "Elite Dangerous: Odyssey Deluxe Edition",
    "Life is Strange: True Colors - Ultimate Edition",
    "Monster Train - The Last Divinity",
    "Roguebook Deluxe Edition",
    "Marvel's Spider-Man Remastered",
    "The Surge 2 Premium Edition",
    "Hitman: Contracts",
    "Cities: Skylines - Sunset Harbor",
    "Hardspace: Shipbreaker",
    "Metro: Exodus Expansion Pass",
    "Legend of Keepers: Career of a Dungeon Manager",
    "Syberia 3",
    "Europa Universalis IV: Wealth of Nations",
    "Overcooked - The Lost Morsel",
    "Gloria Victis: Medieval MMORPG",
    "Shadowrun: Dragonfall (Director's Cut)",
    "Turmoil: The Heat Is On",
    "Dragon Ball FighterZ: FighterZ Pass",
    "Devil May Cry 3: Special Edition",
    "Shift Happens",
    "Project Highrise",
    "LEGO DC Super-Villains Season Pass",
    "Dredge Digital Deluxe Edition",
    "Company of Heroes Complete Pack",
    "Driving School Simulator",
    "Solasta: Crown of the Magister - Lost Valley",
    "Endless Space 2 Definitive Edition",
    "Batora: Lost Haven",
    "Star Wars Jedi Knight Collection",
    "Fights in Tight Spaces",
    "Guilty Gear -Strive- Deluxe Edition",
    "Payday 3",
    "ZUSI 3 - Aerosoft Edition",
    "Overcooked! 2 - Too Many Cooks Pack",
    "Ghost of a Tale",
    "A Normal Lost Phone",
    "Alone In The Dark: The New Nightmare",
    "Tourist Bus Simulator",
    "Post Scriptum (uncut)",
    "Sanctum 2",
    "Sword Art Online: Fatal Bullet",
    "Cossacks: Back to War",
    "Sniper Elite 4 Season Pass",
    "One Piece: Burning Blood Gold Pack",
    "Star Wars Jedi Knight II: Jedi Outcast",
    "Absolver",
    "Golf With Your Friends",
    "Sifu Digital Deluxe Edition",
    "The Legend of Zelda: Breath of the Wild",
    "Red Dead Redemption 2",
    "The Witcher 3: Wild Hunt",
    "Super Mario Odyssey",
    "Grand Theft Auto V",
    "The Last of Us Part II",
    "Halo: Master Chief Collection",
    "Animal Crossing: New Horizons",
    "Minecraft",
    "God of War",
    "Forza Horizon 4",
    "Super Smash Bros. Ultimate",
    "Cyberpunk 2077",
    "Splatoon 2",
    "Call of Duty: Warzone",
    "Assassin's Creed Valhalla",
    "FIFA 22",
    "Pokémon Sword and Shield",
    "Gears 5",
    "Spider-Man: Miles Morales",
    "The Elder Scrolls V: Skyrim",
    "Dark Souls III",
    "Uncharted 4: A Thief's End",
    "Resident Evil Village",
    "Monster Hunter: World",
    "Doom Eternal",
    "Super Mario 3D World + Bowser's Fury",
    "Sekiro: Shadows Die Twice",
    "Bloodborne",
    "Destiny 2",
    "Mortal Kombat 11",
    "Sackboy: A Big Adventure",
    "Ratchet & Clank: Rift Apart",
    "Ori and the Will of the Wisps",
    "Control",
    "Death Stranding",
    "Ghost of Tsushima",
    "Horizon Zero Dawn",
    "Star Wars Jedi: Fallen Order",
    "Dragon Ball Z: Kakarot",
    "Persona 5 Royal",
    "Demon's Souls",
    "The Last of Us Remastered",
    "Final Fantasy VII Remake",
    "The Legend of Zelda: Link's Awakening",
    "Mario Kart 8 Deluxe",
    "Luigi's Mansion 3",
    "New Super Mario Bros. U Deluxe",
    "Super Mario Party",
    "Mario & Sonic at the Olympic Games Tokyo 2020",
    "Ring Fit Adventure",
    "Just Dance 2021",
    "The Legend of Zelda: Tears of the Kingdom",
    "Pokémon: Let's Go, Pikachu! and Let's Go, Eevee!",
    "Pokémon Brilliant Diamond and Shining Pearl",
    "Pokémon Legends: Arceus",
    "Pokémon Mystery Dungeon: Rescue Team DX",
    "Pokémon Snap",
    "Elden Ring",
    "Battlefield 2042",
    "Far Cry 6",
    "Halo Infinite",
    "Dying Light 2",
    "Back 4 Blood",
    "The Elder Scrolls VI",
    "Starfield",
    "GhostWire: Tokyo",
    "Deathloop",
    "God of War Ragnarok",
    "Gran Turismo 7",
    "Gotham Knights",
    "Riders Republic",
    "Rainbow Six Extraction",
    "The Lord of the Rings: Gollum",
    "The Callisto Protocol",
    "The Outlast Trials",
    "Ghost of Tsushima",
    "Hogwarts Legacy",
    "Kena: Bridge of Spirits",
    "Little Devil Inside",
    "Marvel's Avengers",
    "Oddworld: Soulstorm",
    "Monster Hunter Rise",
    "No More Heroes 3",
    "Monster Hunter: World",
    "Xenoblade Chronicles: Definitive Edition",
    "Xenoblade Chronicles 2",
    "Xenoblade Chronicles 3",
    "Xenoblade Chronicles X",
    "The Legend of Zelda: Skyward Sword HD",
    "EA SPORTS FC 24",
    "Cities: Skylines",
    "Cities: Skylines II",
    "The Sims 4",
    "The Lords of the Fallen",
    "Project Zomboid",
    "Minecraft Dungeons",
    "Football Manager 2024",
    "Terraria",
    "Payday 2",
    "Rust",
    "The Legend of Zelda: Ocarina of Time",
    "The Legend of Zelda: A Link to the Past",  
    "The Legend of Zelda: Majora's Mask",     
    "The Legend of Zelda: Twilight Princess",     
    "The Legend of Zelda: The Wind Waker",     
    "The Legend of Zelda: A Link Between Worlds",     
    "The Legend of Zelda: Phantom Hourglass",     
    "The Legend of Zelda: Spirit Tracks",     
    "The Legend of Zelda: Skyward Sword",
    "Euro Truck Simulator 2"
]