allowed_games = [
    "The Legend of Zelda: Breath of the Wild",
    "Red Dead Redemption 2",
    "The Witcher 3: Wild Hunt",
    "Super Mario Odyssey",
    "Grand Theft Auto V",
    "The Last of Us Part II",
    "Halo: Master Chief Collection",
    "Animal Crossing: New Horizons",
    "Minecraft",
    "God of War",
    "Forza Horizon 4",
    "Super Smash Bros. Ultimate",
    "Cyberpunk 2077",
    "Splatoon 2",
    "Call of Duty: Warzone",
    "Assassin's Creed Valhalla",
    "FIFA 22",
    "Pokémon Sword and Shield",
    "Gears 5",
    "Spider-Man: Miles Morales",
    "The Elder Scrolls V: Skyrim",
    "Dark Souls III",
    "Uncharted 4: A Thief's End",
    "Resident Evil Village",
    "Monster Hunter: World",
    "Doom Eternal",
    "Super Mario 3D World + Bowser's Fury",
    "Sekiro: Shadows Die Twice",
    "Bloodborne",
    "Destiny 2",
    "Mortal Kombat 11",
    "Sackboy: A Big Adventure",
    "Ratchet & Clank: Rift Apart",
    "Ori and the Will of the Wisps",
    "Control",
    "Death Stranding",
    "Ghost of Tsushima",
    "Horizon Zero Dawn",
    "Star Wars Jedi: Fallen Order",
    "Dragon Ball Z: Kakarot",
    "Persona 5 Royal",
    "Demon's Souls",
    "The Last of Us Remastered",
    "Final Fantasy VII Remake",
    "The Legend of Zelda: Link's Awakening",
    "Mario Kart 8 Deluxe",
    "Luigi's Mansion 3",
    "New Super Mario Bros. U Deluxe",
    "Super Mario Party",
    "Mario & Sonic at the Olympic Games Tokyo 2020",
    "Ring Fit Adventure",
    "Just Dance 2021",
    "The Legend of Zelda: Tears of the Kingdom",
    "Pokémon: Let's Go, Pikachu! and Let's Go, Eevee!",
    "Pokémon Brilliant Diamond and Shining Pearl",
    "Pokémon Legends: Arceus",
    "Pokémon Mystery Dungeon: Rescue Team DX",
    "Pokémon Snap",
    "Elden Ring",
    "Battlefield 2042",
    "Far Cry 6",
    "Halo Infinite",
    "Dying Light 2",
    "Back 4 Blood",
    "The Elder Scrolls VI",
    "Starfield",
    "GhostWire: Tokyo",
    "Deathloop",
    "God of War Ragnarok",
    "Gran Turismo 7",
    "Gotham Knights",
    "Riders Republic",
    "Rainbow Six Extraction",
    "The Lord of the Rings: Gollum",
    "The Callisto Protocol",
    "The Outlast Trials",
    "Ghost of Tsushima",
    "Hogwarts Legacy",
    "Kena: Bridge of Spirits",
    "Little Devil Inside",
    "Marvel's Avengers",
    "Oddworld: Soulstorm",
    "Monster Hunter Rise",
    "No More Heroes 3",
    "Monster Hunter: World",
    "Xenoblade Chronicles: Definitive Edition",
    "Xenoblade Chronicles 2",
    "Xenoblade Chronicles 3",
    "Xenoblade Chronicles X",
    "The Legend of Zelda: Skyward Sword HD",
    "EA SPORTS FC 24",
    "Cities: Skylines",
    "Cities: Skylines II",
    "The Sims 4",
    "The Lords of the Fallen",
    "Project Zomboid",
    "Minecraft Dungeons",
    "Football Manager 2024",
    "Terraria",
    "Payday 2",
    "Rust",
    "The Legend of Zelda: Ocarina of Time",
    "The Legend of Zelda: A Link to the Past",
    "The Legend of Zelda: Majora's Mask",
    "The Legend of Zelda: Twilight Princess",
    "The Legend of Zelda: The Wind Waker",
    "The Legend of Zelda: A Link Between Worlds",
    "The Legend of Zelda: Phantom Hourglass",
    "The Legend of Zelda: Spirit Tracks",
    "The Legend of Zelda: Skyward Sword"
]
