allowed_games = [
"The Last of Us Part II",
"Ghost of Tsushima: Legends",
"Marvel's Spider-Man: Game of the Year Edition",
"Watch Dogs: Legion PS4 & PS5",
"Grand Theft Auto V: Premium Edition",
"Tony Hawk's Pro Skater 1 + 2",
"Mortal Kombat 11",
"STAR WARS: Squadrons",
"Need for Speed Heat Deluxe Edition",
"FINAL FANTASY VII REMAKE",
"Assassin's Creed Odyssey Ultimate Edition",
"God of War",
"PGA TOUR 2K21",
"Mafia: Definitive Edition",
"Nioh 2",
"Marvel's Iron Man VR",
"WWE 2K Battlegrounds",
"Project CARS 3",
"The Division 2 - Warlords of New York - Ultimate Edition",
"Need for Speed Hot Pursuit Remastered",
"UFC 4",
"No Man's Sky PS4 & PS5",
"Cuphead",
"Ghostrunner",
"ARK: Survival Evolved",
"Skater XL",
"The Sims 4",
"Crash Team Racing Nitro-Fueled",
"The Last Of Us Remastered ",
"Mafia: Trilogy",
"Borderlands 3 PS4 &  PS5",
"Tom Clancy's Ghost Recon Breakpoint",
"DARK SOULS: REMASTERED",
"SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated",
"Fallout 76",
"Stranded Deep",
"Far Cry 5",
"The Outer Worlds",
"UNCHARTED 4: A Thiefs End",
"The Walking Dead: Saints & Sinners - Standard Edition",
"Spyro Reignited Trilogy",
"PUBG: BATTLEGROUNDS",
"13 Sentinels: Aegis Rim",
"NASCAR Heat 5",
"Wreckfest",
"World War Z",
"Mortal Shell",
"Control: Ultimate Edition",
"Maneater PS4 & PS5",
"Maneater PS4 & PS5",
"Dreams",
"RESIDENT EVIL 7 biohazard",
"Saints Row: The Third Remastered",
"Destroy All Humans!",
"Kingdoms of Amalur: Re-Reckoning",
"Yu-Gi-Oh! Legacy of the Duelist: Link Evolution",
"Risk of Rain 2",
"The Legend of Heroes: Trails of Cold Steel IV Digital Deluxe Edition",
"GORN",
"Shadow of the Tomb Raider Definitive Edition",
"Plants vs. Zombies: Battle for Neighborville",
"KINGDOM HEARTS All-In-One Package",
"Amnesia: Rebirth",
"Fallout 4: Game of the Year Edition",
"Attack on Titan 2: Final Battle",
"ACE COMBAT 7: SKIES UNKNOWN",
"Streets Of Rage 4",
"The Elder Scrolls V: Skyrim VR",
"Devil May Cry 5",
"Monster Hunter World: Iceborne Digital Deluxe",
"Wasteland 3",
"LEGO Marvel Super Heroes",
"Hunt: Showdown",
"KINGDOM HEARTS HD 1.5 +2.5 ReMIX",
"SMITE Ultimate God Pack",
"Street Fighter V: Champion Edition",
"MOBILE SUIT GUNDAM EXTREME VS. MAXIBOOST ON",
"Battlefield V Definitive Edition",
"Cities: Skylines - PlayStation4 Edition",
"Attack on Titan 2",
"Crysis Remastered",
"LEGO Batman 3: Beyond Gotham",
"Judgment",
"Devil May Cry HD Collection & 4SE Bundle",
"Yakuza 6: The Song of Life",
"Yakuza Kiwami 2",
"WRC 9 FIA World Rally Championship PS4 & PS5",
"Assassins Creed Origins Gold Edition",
"STAR WARS Battlefront II: Celebration Edition",
"RIDE 4",
"Arizona Sunshine",
"Kingdom Come: Deliverance Royal Edition",
"A Plague Tale: Innocence",
"Darksiders Genesis",
"CODE VEIN Deluxe Edition",
"Ghostbusters: The Video Game Remastered",
"Assetto Corsa Competizione",
"TALES OF BERSERIA",
"Budget Cuts",
"Starfield Digital Premium Edition",
"Warhammer 40.000: Dawn of War II Master Collection",
"Risen 2: Dark Waters",
"Call of Juarez: Bound in Blood",
"Farming Simulator 22 - Premium Edition",
"Old World - The Sacred and The Profane",
"Endzone - A World Apart Complete Edition",
"Prison Simulator",
"Cities: Skylines - Content Creator Pack: Seaside Resorts",
"SBK 22",
"Earth Defense Force 5",
"The Jackbox Party Pack 8",
"NBA 2K22",
"Patrician III",
"Ride 5",
"Journey to the Savage Planet",
"Destiny 2: Legendary Edition",
"Pure Farming 2018 - Digital Deluxe Edition",
"Total War: Rome II - Wrath of Sparta",
"Sword Art Online: Alicization Lycoris Deluxe Edition",
"Sniper Ghost Warrior 3",
"Panzer Corps 2",
"Overcooked! 2 - Carnival of Chaos",
"Sacred Gold",
"No Man's Sky",
"Gloomhaven",
"Treasure Hunter Simulator",
"Dead by Daylight: The 80's Suitcase",
"BlazBlue: Centralfiction",
"Tropico 5",
"Tannenberg",
"LEGO Marvel Super Heroes 2",
"The Jackbox Party Pack 3",
"Marvel's Avengers - The Definitive Edition",
"Sid Meier’s Civilization VI: Leader Pass",
"Frozen Flame",
"MotoGP 23",
"The Jackbox Party Quintpack",
"Autobahn Police Simulator 3",
"Orcs Must Die! 3 - Cold as Eyes",
"Creaks",
"Elite Dangerous: Odyssey Deluxe Edition",
"Life is Strange: True Colors - Ultimate Edition",
"Monster Train - The Last Divinity",
"Roguebook Deluxe Edition",
"Marvel's Spider-Man Remastered",
"The Surge 2 Premium Edition",
"Hitman: Contracts",
"Cities: Skylines - Sunset Harbor",
"Hardspace: Shipbreaker",
"Metro: Exodus Expansion Pass",
"Legend of Keepers: Career of a Dungeon Manager",
"Syberia 3",
"Europa Universalis IV: Wealth of Nations",
"Overcooked - The Lost Morsel",
"Gloria Victis: Medieval MMORPG",
"Shadowrun: Dragonfall (Director's Cut)",
"Turmoil: The Heat Is On",
"Dragon Ball FighterZ: FighterZ Pass",
"Devil May Cry 3: Special Edition",
"Shift Happens",
"Project Highrise",
"LEGO DC Super-Villains Season Pass",
"Dredge Digital Deluxe Edition",
"Company of Heroes Complete Pack",
"Driving School Simulator",
"Solasta: Crown of the Magister - Lost Valley",
"Endless Space 2 Definitive Edition",
"Batora: Lost Haven",
"Star Wars Jedi Knight Collection",
"Fights in Tight Spaces",
"Guilty Gear -Strive- Deluxe Edition",
"Payday 3",
"ZUSI 3 - Aerosoft Edition",
"Overcooked! 2 - Too Many Cooks Pack",
"Ghost of a Tale",
"A Normal Lost Phone",
"Alone In The Dark: The New Nightmare",
"Tourist Bus Simulator",
"Post Scriptum (uncut)",
"Sanctum 2",
"Sword Art Online: Fatal Bullet",
"Cossacks: Back to War",
"Sniper Elite 4 Season Pass",
"One Piece: Burning Blood Gold Pack",
"Star Wars Jedi Knight II: Jedi Outcast",
"Absolver",
"Golf With Your Friends",
"Sifu Digital Deluxe Edition",
"The Legend of Zelda: Breath of the Wild",
"Red Dead Redemption 2",
"The Witcher 3: Wild Hunt",
"Super Mario Odyssey",
"Grand Theft Auto V",
"The Last of Us Part II",
"Halo: Master Chief Collection",
"Animal Crossing: New Horizons",
"Minecraft",
"God of War",
"Monster Hunter: World",
"Doom Eternal"
]